"""empty message

Revision ID: 90362ff2399d
Revises: f77b0eb0bdf2
Create Date: 2020-03-07 05:15:08.783936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90362ff2399d'
down_revision = 'f77b0eb0bdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_ibfk_2', 'chats', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('chats_ibfk_2', 'chats', 'users', ['user2_username'], ['username'])
    # ### end Alembic commands ###
