"""empty message

Revision ID: 9ecda93f869c
Revises: de0a947e6b99
Create Date: 2020-03-07 04:34:54.702207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecda93f869c'
down_revision = 'de0a947e6b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['writer_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
