"""empty message

Revision ID: f3b986a4532d
Revises: 90362ff2399d
Create Date: 2020-03-07 05:29:07.512281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b986a4532d'
down_revision = '90362ff2399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['user2_username'], ['username'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
