"""empty message

Revision ID: f77b0eb0bdf2
Revises: 9ecda93f869c
Create Date: 2020-03-07 05:13:48.629926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77b0eb0bdf2'
down_revision = '9ecda93f869c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_ibfk_3', 'chats', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('chats_ibfk_3', 'chats', 'users', ['writer_username'], ['username'])
    # ### end Alembic commands ###
